repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black .
          language: system
          always_run: true
          pass_filenames: false
        - id: autoflake
          name: autoflake
          entry: autoflake --recursive .
          language: system
          always_run: true
          pass_filenames: false
