services:
  redis:
    image: redis:latest
    expose:
      - '6379/tcp'
    networks:
      - main

  mongo:
    image: mongo:6
    expose:
      - '27017/tcp'
    networks:
      - main

  aws:
    container_name: aws
    image: localstack/localstack:3.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-west-2}
      DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-west-2}
      SQS_ENDPOINT_STRATEGY: path
      SERVICES: sqs
      LOCALSTACK_HOST: aws
      DEBUG: 1
      LS_LOG: trace
    volumes:
      - ./containers/localstack:/etc/localstack/init/ready.d
    networks:
      - main

  django-q2:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    environment:
      AWS_ENDPOINT_URL: http://aws:4566
      AWS_REGION: ${AWS_REGION:-us-west-2}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-west-2}
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
      - aws
    networks:
      - main

networks:
  main:
