services:
  web:
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    build: .
    volumes:
      - .:/app

  django-q:
    restart: always
    command: bash -c "python manage.py migrate && python manage.py qcluster"
    build: .
    volumes:
      - .:/app
