|
#!/bin/bash

set -x
unitAddress()
{
    py_script="
import sys
import yaml

status_yaml=yaml.safe_load(sys.stdin)
unit = status_yaml['applications']['$1']['units']
units = list(unit.keys())
print(unit[units[0]]['public-address'])
"
    juju status -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$1" --format yaml | env python3 -c "$py_script"
}


ansible-playbook -i $(unitAddress ubuntu), \
             --ssh-common-args '-o StrictHostKeyChecking=no' \
             --key-file /var/lib/jenkins/.local/share/juju/ssh/juju_id_rsa \
             -u ubuntu \
             $PLAYBOOK
