data_reading:
  # define readers to activate in open file wizard
  readers:
    - abi_l1b
    - abi_l2_nc
    - fci_l1c_nc
    - fci_l2_nc
    - fci_l2_bufr
    - fci_l2_grib
    - li_l1b_nc
    - li_l2_nc
    - seviri_l1b_hrit
    - seviri_l1b_native
    - seviri_l2_binary
    - seviri_l2_bufr
    - seviri_l2_grib
    - avhrr_l1b_eps
    - vii_l1b_nc
    - gld360_ualf2
    - modis_l1b
    - modis_l2
    - viirs_l1b
    - viirs_l2
