---
name: s3-buckets

---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets
Resources:
  {% for n in range(buckets_count|int) %}
  S3Bucket{{ loop.index0 }}:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{ env }}-{{ bucket_name_prefix }}{{ loop.index0 }}-{{ region }}
  {% endfor -%}
