name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.9
          - python-version: 3.9
          - python-version: 3.9
          - python-version: 3.9
          - python-version: 3.9
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/cache@v4
        with:
          path: $HOME/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
      - uses: actions/checkout@v2
      - run: pip install -U pip wheel setuptools
      - run: pip install -U coveralls tox tox-gh-actions
      - run: tox
      #- run: coveralls