name: Lint and test pybikes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install
    - name: lint
      run: make lint
    - name: Core tests
      run: make test-base
    - name: Instance tests (not update)
      run: make test-instances
    - name: Update instance tests (fail ok)
      run: |
        if [[ "${{ matrix.python-version }}" == "2.7" ]]; then
          make test-update-instances
        else
          make test-update-instances T_FLAGS+="-n 10"
        fi
      continue-on-error: true