name: Test
on:
  - push
  - pull_request_target
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: flake8
  unit-test:
    needs: lint
    strategy:
      matrix:
        python: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v2
      - run: pip install -e .[test]
      - run: ./test/run_test.sh