name: Django Tests

on:
  push:
      - name: Run tests with Python ${{ matrix.python-version }} and Django ${{ matrix.django-version }}
        run: |
          TOX_ENV=$(echo "py${{ matrix.python-version}}-django${{ matrix.django-version}}" | tr -d .)
          python -m tox -e $TOX_ENV

      - name: Publish coverage results