# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Repostat for Ubuntu 20.04

on:
  push:
jobs:
  ubuntu_build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Check generated report integrity
      run: python tools/check_report_files.py --is-relocatable /tmp

    - name: Check unit tests
      run: |
        git config --global user.name "Repo Stat"
        git config --global user.email "ci@repo.stat"
        python -m unittest -v