name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_ubuntu:
    name: 'Ubuntu'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tox
      run: |
        python3 -m pip install --user tox
        PATH="$HOME/.local/bin/:$PATH" tox -q -p all