name: Exhaustive Tests

on:
  schedule:
  # Run every morning at 9AM UTC
  - cron: 0 9 * * *

jobs:
  test:
    name: Test ${{ matrix.sport }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 54
      matrix:
        python-version: ["3.9", "3.10"]
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        sport: ['MLB', 'NBA', 'NCAAB', 'NCAAF', 'NFL', 'NHL']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test MLB
      if: matrix.sport == 'MLB'
      run:
        python tests/exhaustive/test_mlb.py
    - name: Test NBA
      if: matrix.sport == 'NBA'
      run:
        python tests/exhaustive/test_nba.py
    - name: Test NCAAB
      if: matrix.sport == 'NCAAB'
      run:
        python tests/exhaustive/test_ncaab.py
    - name: Test NCAAF
      if: matrix.sport == 'NCAAF'
      run:
        python tests/exhaustive/test_ncaaf.py
    - name: Test NFL
      if: matrix.sport == 'NFL'
      run:
        python tests/exhaustive/test_nfl.py
    - name: Test NHL
      if: matrix.sport == 'NHL'
      run:
        python tests/exhaustive/test_nhl.py