name: Run CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} testing env
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test
      run: cd tests && bash run_tests.sh

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]