name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ["3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install Markdown python-markdown-math pymdown-extensions
          python -m pip install docutils textile pygments codecov
      - name: Install the project
        run: python setup.py install
      - name: Run tests
        run: coverage run -m unittest discover -s tests -v
      - name: Upload reports to Codecov
        run: codecov