name: lexpy
on: push

jobs:
  unittests:
    name: lexpy unitests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, ubuntu-latest]
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -e .
        pip install coverage

    - name: Run Unittests
      run: |
        coverage run -m unittest discover -s lexpy/tests
        coverage combine
        coverage report -m