name: Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install radare2 5.8.0
      run: |
        wget https://github.com/radareorg/radare2/releases/download/5.8.0/radare2_5.8.0_amd64.deb
        sudo dpkg -i radare2_5.8.0_amd64.deb
        r2 -v
    - name: Install python dependencies
      run: pip3 install -r python/requirements_ci.txt
    - name: Build python module
      run: make -C python build
    - name: Install r2papi.py
      run: sudo make -C python install || true
    - name: Test the r2api
      run: rarun2 timeout=10 system="make -C python test"